[package]
name = "gantt"
version = "0.1.0"
authors = ["Richard Fryer <richard@richardfryer.com>"]

[dependencies]
rocket = "0.2.2"
rocket_codegen = "0.2.2"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["handlebars_templates"]